name: AI Agent (tasks → code → PR via MCP)

on:
  push:
    paths:
      - "tasks/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  mcp-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for MCP GitHub server via npx)
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run agent (all ops via MCP)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-5
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: ${{ github.ref_name }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python agent/agent_mcp_github.py


